### ISSUE TITLE
Profiles broken

### ISSUE THREAD

**Issue by benlazer1** [Saltssaumure/xp-discord-theme#18]
Whenever I open someones profile, in server or DM, the rest of the screen goes blue screen of death.
![Screen](https://github.com/Saltssaumure/xp-discord-theme/assets/155141313/a2cd4f19-8219-405d-9271-c8d0452344db)

**Comment by Saltssaumure** [comment]
This is intentional, any modal (popups that dim the rest of the screen in default discord) is styled in this way. If you want to disable this effect, see the [customisation instructions](https://github.com/Saltssaumure/xp-discord-theme#customisation) for how to set `--bsod-color` to `transparent` and `--bsod-text` to `""`.
